import type { Metadata } from "next";
import { Cabin, Changa_One, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/navbar";
import { AuthProvider } from "@/components/provider/AuthProvider";
import { Toaster } from "sonner";
const changaOne = Changa_One({
  subsets : ["latin"],
  weight : ["400"],
  variable : "--font-changa-one",
  display : "swap"
})
const cabin = Cabin({
  subsets : ['latin'],
  weight : ['400', '500', '600', '700'],
  variable : "--font-cabin",
  display : "swap"
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${cabin.variable} ${geistMono.variable} ${changaOne.variable} antialiased`}
      >
        <AuthProvider>

        <Navbar/>
        {children}
        <Toaster/>
        </AuthProvider>
      </body>
    </html>
  );
}
